name: Test-Proxy
version: "0.0.0001"
panel_icon: "mdi:microsoft-visual-studio-code"
panel_title: Proxy_DEV
slug: ha-custom-proxy
description: Proxy Addon to Add Custom Applications to Homeassistant
url: "https://github.com/marvin1309/ha_custom_app_proxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:5010]/"
watchdog: "http://[HOST]:[PORT:5010]/"
ingress: true
ingress_port: 5010
ingress_entry: /
panel_admin: false
ports:
  5010/tcp: 5010
ports_description:
  5010/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "Your Service IP:Your Port"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
